name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space ðŸ§¹
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /home/linuxbrew
          df -h

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean Docker before build
        run: |
          docker system prune -af || true
          docker volume prune -f || true
          df -h

      - name: Build Docker Image
        run: docker build -t fastapi-app .

      - name: Save Docker image as tar
        run: |
          docker save fastapi-app -o fastapi-app.tar
          ls -lh fastapi-app.tar
          df -h

      - name: Run Trivy Scan (TAR mode)
        run: |
          docker run --rm \
            -v $(pwd):/project \
            aquasec/trivy:latest image \
            --input /project/fastapi-app.tar \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            --no-progress

      - name: Run kube-score (lint Kubernetes manifests)
        run: |
          docker run --rm \
            -v $(pwd):/project \
            zegl/kube-score:latest \
              kube-score score --output-format ci /project/deployment.yaml
